export const metadata = {
    title: "Minhas Tarefas",
    description: "Generated by create next app",
};

export default function LayoutLogin({ children }) {
    return (
        <body className={`flex  flex-col w-screen h-screen`}>
            <main>{children}</main>
        </body>
    );
}
