"use client";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";
import { AppProvider } from "@/data/context/AppContext";
import useAppData from "@/data/hooks/useAppData";

export const metadata = {
    title: "Minhas Tarefas",
    description: "Generated by create next app",
};

export default function LayoutLogin({ children }) {
    return (
        <body className={`flex  flex-col w-screen h-screen`}>
            <main className="flex flex-1 w-full">{children}</main>
        </body>
    );
}
