import "./globals.css";
import { AppProvider } from "@/data/context/AppContext";

export const metadata = {
  title: "Minhas Tarefas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppProvider>
        {children}
      </AppProvider>
    </html>
  );
}
